In [3]:
import pandas as pd

df = pd.read_excel("consultas.xlsx")
print(df.head())

   IdConsulta  IdCorrelativo  IdTenant               FechaHora  Turno  \
0       56488           2025       254 2025-06-26 07:15:01.113     25
1       56489           2025       254 2025-06-26 07:15:25.033     26
2       56491           2025       254 2025-06-26 07:16:44.893     28
3       56492           2025       254 2025-06-26 07:17:19.800     29
4       56493           2025       254 2025-06-26 07:17:25.300     30

   IdClinica                    Clinica  IdTipoClinica       TipoClinica  \
0         67               PE-Pediatria              1  CONSULTA EXTERNA
1         62             Gi-Ginecologia              1  CONSULTA EXTERNA
2         61              MA-MATERNIDAD              1  CONSULTA EXTERNA
3         67               PE-Pediatria              1  CONSULTA EXTERNA
4         70  EMI-EMER Medicina Interna              2        EMERGENCIA

   IdServicio  ... Papanicolaou  IVAA TamizajeVIFVBG CrecimientoYDesarrollo  \
0          48  ...            0     0              0                      0
1          10  ...            0     0              0                      0
2          54  ...            0     0              0                      0
3          48  ...            0     0              0                      0
4          37  ...            0     0              0                      0

   FueReferido VieneContraReferido VieneReferido  FueContraReferido  \
0            0                   0             0                  0
1            0                   0             0                  0
2            0                   0             0                  0
3            0                   0             0                  0
4            0                   0             0                  0

  SincronizarPaciente  SincronizarConsulta
0                   1                    1
1                   1                    1
2                   1                    1
3                   1                    1
4                   1                    1

[5 rows x 63 columns]

In [2]:
# instalar openpyxl
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\vcuch\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\vcuch\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
# Cantidad de registros por columna
df.count()

IdConsulta             190140
IdCorrelativo          190140
IdTenant               190140
FechaHora              190140
Turno                  190140
                        ...
VieneContraReferido    190140
VieneReferido          190140
FueContraReferido      190140
SincronizarPaciente    190140
SincronizarConsulta    190140
Length: 63, dtype: int64

In [ ]:
# Columnas del DataFrame
df.columns

Index(['IdConsulta', 'IdCorrelativo', 'IdTenant', 'FechaHora', 'Turno',
       'IdClinica', 'Clinica', 'IdTipoClinica', 'TipoClinica', 'IdServicio',
       'Servicio', 'IdDepartamentoHospitalario', 'DepartamentoHospitalario',
       'SeguroSocial', 'HistoriaClinica', 'FechaNacimiento', 'Sexo',
       'IdPueblo', 'Pueblo', 'IdComunidadLinguistica', 'ComunidadLinguistica',
       'MigranteAgricola', 'EdadDias', 'EdadMeses', 'EdadAnios',
       'IdDiscapacidad', 'Discapacidad', 'IdEstadoCivil', 'EstadoCivil',
       'IdEscolaridad', 'Escolaridad', 'IdProfesion', 'Profesion',
       'IdDepartamento', 'Departamento', 'IdMunicipio', 'Municipio',
       'IdComunidad', 'Comunidad', 'Diagnostico', 'CIE10', 'CIE10Descripcion',
       'IdMedico', 'Medico', 'Nuevo', 'Primera', 'Reconsulta', 'InterConsulta',
       'Emergencia', 'Prenatal', 'Puerperio', 'PlanificacionFamiliar',
       'ProfilaxiaSexual', 'Papanicolaou', 'IVAA', 'TamizajeVIFVBG',
       'CrecimientoYDesarrollo', 'FueReferido', 'VieneContraReferido',
       'VieneReferido', 'FueContraReferido', 'SincronizarPaciente',
       'SincronizarConsulta'],
      dtype='str')

In [11]:
# Información general del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 190140 entries, 0 to 190139
Data columns (total 63 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   IdConsulta                  190140 non-null  int64
 1   IdCorrelativo               190140 non-null  int64
 2   IdTenant                    190140 non-null  int64
 3   FechaHora                   190140 non-null  datetime64[us]
 4   Turno                       190140 non-null  int64
 5   IdClinica                   190140 non-null  int64
 6   Clinica                     190140 non-null  str
 7   IdTipoClinica               190140 non-null  int64
 8   TipoClinica                 190140 non-null  str
 9   IdServicio                  190140 non-null  int64
 10  Servicio                    190140 non-null  str
 11  IdDepartamentoHospitalario  190140 non-null  int64
 12  DepartamentoHospitalario    190140 non-null  str
 13  SeguroSocial                564 non-null     object
 14  HistoriaClinica             190139 non-null  float64
 15  FechaNacimiento             151776 non-null  datetime64[us]
 16  Sexo                        190140 non-null  str
 17  IdPueblo                    190140 non-null  int64
 18  Pueblo                      190140 non-null  str
 19  IdComunidadLinguistica      190140 non-null  int64
 20  ComunidadLinguistica        190140 non-null  str
 21  MigranteAgricola            190140 non-null  int64
 22  EdadDias                    190140 non-null  int64
 23  EdadMeses                   190140 non-null  int64
 24  EdadAnios                   190140 non-null  int64
 25  IdDiscapacidad              190140 non-null  int64
 26  Discapacidad                4956 non-null    str
 27  IdEstadoCivil               190140 non-null  int64
 28  EstadoCivil                 150894 non-null  str
 29  IdEscolaridad               190140 non-null  int64
 30  Escolaridad                 93554 non-null   str
 31  IdProfesion                 190140 non-null  int64
 32  Profesion                   104402 non-null  str
 33  IdDepartamento              190140 non-null  int64
 34  Departamento                190077 non-null  str
 35  IdMunicipio                 190140 non-null  int64
 36  Municipio                   189701 non-null  str
 37  IdComunidad                 190140 non-null  int64
 38  Comunidad                   19441 non-null   str
 39  Diagnostico                 189919 non-null  object
 40  CIE10                       189260 non-null  str
 41  CIE10Descripcion            189260 non-null  str
 42  IdMedico                    190140 non-null  int64
 43  Medico                      190140 non-null  str
 44  Nuevo                       190140 non-null  int64
 45  Primera                     190140 non-null  int64
 46  Reconsulta                  190140 non-null  int64
 47  InterConsulta               190140 non-null  int64
 48  Emergencia                  190140 non-null  int64
 49  Prenatal                    190140 non-null  int64
 50  Puerperio                   190140 non-null  int64
 51  PlanificacionFamiliar       190140 non-null  int64
 52  ProfilaxiaSexual            190140 non-null  int64
 53  Papanicolaou                190140 non-null  int64
 54  IVAA                        190140 non-null  int64
 55  TamizajeVIFVBG              190140 non-null  int64
 56  CrecimientoYDesarrollo      190140 non-null  int64
 57  FueReferido                 190140 non-null  int64
 58  VieneContraReferido         190140 non-null  int64
 59  VieneReferido               190140 non-null  int64
 60  FueContraReferido           190140 non-null  int64
 61  SincronizarPaciente         190140 non-null  int64
 62  SincronizarConsulta         190140 non-null  int64
dtypes: datetime64[us](2), float64(1), int64(41), object(2), str(17)
memory usage: 91.4+ MB

In [24]:
df["SeguroSocial"].unique()

array([nan, '0254-2016-0117-59', 'S. E. 99744', '2016-0221-56',
       'S. E. 2017-0287-82', 'S. E. 2023-0153-76', '2010 0260 8875',
       'SE 2024-0353-11', 'S. E. 2015-0340-72', 'SE2024-0161-45',
       'SE2025-0089-33', 'SE2019-0173-86', 'SE-2015-0154-10', 173205592,
       '0254-2015-0130-69', '0254-2025-0115-87', 'S. E. 2025-0138-05',
       'S. E. 2025-0138-98', '0254-2025-0144-70', 'E. S. 2023-0122-83',
       'S. E. 2025-0147-76', 'S. E. 2025-0147-83', 'S. E. 2025-0157-12',
       '  ', 'S.E. PO14V2B', ' ', 'S.E-2026-0024-99',
       'S. E. 2025-0019-59', 'S. E', 'S.E. 2024-0186-53', 'S.E. N411DKG',
       113771, '102-183-00006', 119630, 'S.E.124542', 'S.E-2026-0038-55',
       'S.E-2025-0358-90', 'S.E.P-2014-0125-22', 'S.E-2026-0060-13',
       'S.E. 2025-0278-65', 'S.E-2020-0076-10', 'S.E -2026-0097-23',
       'S.E.P-2023-0188-67', 'S.E-2026-0025-97', 'S.E-2023-0046-70',
       'S.E-2026-0061-70', 'S. E.-2026-0061-99', 'S.E-2017-0337-95',
       'S.E. 2026-0058-03', 'S.E-2025-0195-68', 'S.E-2026-0063-99',
       'S.E-2023-0166-41', 'S.E-2023-0166-40', 'S.E-2024-0234-09',
       'S.E-2026-0056-81', 'S.E-2026-0064-81', 'S.E-2026-0064-91',
       'S.E-2015-0355-78', 'S. E  P 2026-0050-68', 'S.E-2015-0407-62',
       'S.E.P-2026-0065-34', 'S.E-2015-0116-35', 'S.E.-2026-0065-70',
       'S.E-2026-0051-72', 'S.E-2014-0220-55', 'S.E-2026-0049-88',
       'S.E-2026-0049-72', 'S.E-2026-0067-01', 'S.E-2026-0067-55',
       'S.E-2018-0056-17', 'S.E-2026-0059-10', 'SE-0254-2015-0276-47',
       'S.E-2015-0376-63', 'S.E. 2024-0255-30', 'S.E. 2023-0156-81',
       'S.E-2021-0236-29', 'S. E.  2022-0159-19', 'S.E-2026-0071-29',
       'S.E. 2026-0071-41', 'SE-0254-2026-0071-64', 'S. E 2017-0264-87',
       'S.E-2026-0072-35', 'S.E-2016-0193-56', 'S. E 2021-0242-06',
       'SE-0254-2018-0251-81', 'SE-0254-2021-0060-73',
       'SE-0254-2025-0281-84', 'SE-0254-2017-0316-70',
       'SE-0254-2025-0010-64', 'S. E.-2025-0210-35',
       'S. E.-20017-0168-79', 'SE-0254-2023-0070-48', 'S.E. 2023-0339-33',
       'S. E.-2025-0119-61', 'S.E 2022-0285-00', 'S.E. 2026-0073-65',
       'IGSS 2026-0073-67', 'S.E. 2020-0149-54', 'S.E 2015-0065-66',
       'S.E 2018-0244-61', 'S.E. 2023-0063-42', 'S.E. 2026-0049-95',
       'SE-0254-2025-0072-15', 'S.E. 2023-0124-86', 'S.E. 2023-0335-39',
       'S. E.-2025-0144-19', 'S.E 2024-0176-05', 'S.E. 2016-0299-20',
       'S.E. 2026-0074-22', 'S.E. 2026-0074-25', 'S.E. 2014-0044-68',
       'S.E. 2023-0064-67', 'S.E. 2023-0260-86', 'S.E 2026-0074-35',
       'S.E.P-2018-0215-06', 'S.E-2025-0328-84', 'S.E-2015-0164-72',
       'S.E-2017-0249-26', 'S.E-2026-0074-71', 'S.E-2026-0034-00',
       'S. E 2026-0074-74', 'S. E  2026-0074-76', 'S.E 2025-0355-19',
       'S.E 2026-0074-85', ' S. E  2025-0316-58', 'S. E2023-0340-54',
       'S. E  2017-0163-85', 'S. E2026-0075-19', 'S. E. 2026-0075-33',
       'S. E  2026-0075-46', 'S.E-2026-0075-38', 'S. E 2011-0030-77',
       'S.E 2022-0097-59', 'S. E 2026-0075-49', 'S. E 2026-0075-52',
       'S. E   2024-0223-49', 'S.E 2017-0193-25', 'S.E.P 2026-0075-67',
       'S.E 2025-0006-81', 'S.E 2026-0075-73', 'S.E P. 2022-0212-97',
       'S.E 2026-0075-77', 'S.E  2023-0203-51', 'S.E-2023-0056-85',
       ' S. E 2015-0279-67', 'S. E  2026-0075-91', 'S.E-2019-0006-17',
       'S.E-2026-0048-29', 'S.E-2018-0274-19', 'S.E-2026-0029-19',
       'S.E-2021-0242-31', 'S. E.-2026-0076-41', 'S.E. 2019-0081-27',
       'S.E 2026-0075-08', 'S. E.-2022-0020-86', 'S. E.-2023-0047-36',
       'S.E. 2024-0039-39', 'S. E.-2025-0339-02', 'S. E.-2023-0161-57',
       'S. E.-2026-0076-62', 'S.E. 2019-0346-27', 'S.E.',
       'S.E. 2026-0076-91', 'S. E.-2026-0076-87', 'S.E. 2026-0076-92',
       'S.E. 2023-0110-97', 'S.E. 2026-0077-06', 'S.E. 2023-0315-35',
       'S.E. 2022-0117-12', 'S.E. 2015-0277-10', 'S.E. 2024-0022-16',
       'S.E 2024-0102-08', 'S.E. 2023-0233-98', 'S.E. 2024-0264-86',
       'S.E-2019-0359-96', 'S. E 2017-0251-42', 'S. E.-2026-0077-79',
       'S.E-2024-0080-11', 'S. E.-2026-0077-82', 'S. E.-2026-0077-86',
       'S.E  2019-0303-17', 'S.E 2026-0078-01', 'S.E 2026-0078-06 ',
       'S. E. P 2016-0283-69', 'S.E 2023-0216-69', 'S.E 2024-0107-82',
       'S.E 2024-0277-84', 'S.E.P 2026-0078-14', 'S. E 2023-0338-47',
       'S. E 2025-0317-08', 'S. E 2026-0078-36', 'S.E 2026-0078-49',
       'S.E. 2024-0035-31', '2016-0393-56S. E ', 'S.E. P 2015-0197-04',
       'S. E 2023-0065-34', 'S.E  2026-0078-85', 'S. E  2026-0078-73',
       'S.E 2026-0078-76', 'S. E P. 2026-0078-81', 'S. E 2016-0307-92',
       'S. E 2023-0056-20', 'S.E.P 2026-0078-88', 'S.E-2020-0131-34',
       'S.E-2023-0020-16', 'S.E. 2026-0079-53', 'S.E. 2022-0098-12',
       'S.E 2014-0162-71', 'S. E  2026-0080-34', 'S.E.P 2022-0132-07',
       'S.E 2026-0080-43', 'S. E 2026-0080-45', 'S.E 2026-0080-52',
       'S.E.P 2026-0080-54', 'S. E. 2014-0048-99', 'S.E 2018-0155-91',
       'S. E 2026-0080-72', 'S.E 2026-0080-76', 'S. E 2026-0080-87',
       'S.E 2018-0124-00', 'S.E 2026-0080-79', 'S. E 2013-0019-47',
       'S. E  2026-0080-83', 'S. E 2026-0080-86', 'S.E 2026-0080-98',
       'S.E 2026-0081-00', 'S.E. 2024-0047-82', 'S.E. 2026-0081-88',
       'S.E-2025-0336-35', 'S.E-2026-0036-59', 'S.E-2014-0241-25',
       'S.E-2026-0082-40', 'S.E-2025-0023-04', 'S.E. 2026-0082-63',
       'S.E. 2023-0107-17', 'S.E. 2026-0082-64', 'S.E-2025-0186-99',
       'S.E. 2026-0082-69', 'S.E. 2023-0188-00', 'S. E.-2026-0082-78',
       'S. E.2026-0082-81', 'S. E.-2026-0082-79', 'S.E 2025-0154-44',
       'S. E.-2022-0253-21', 'S.E. 2017-0301-39', 'S.E. 2026-0083-02',
       'S.E. 2015-0239-92', 'S.E. 2017-0146-40', 'S.E. 2016-0151-61',
       'S.E. 2020-0052-83', 'S.E. 2015-0327-72', 'S. E 2025-0179-43',
       'S.E 2026-0041-93', 'S.E-2025-0337-86', 'S.E-2017-0049-97',
       'S.E-2026-0082-59', 'S.E-2018-0294-77', 'S. E 2018-0120-74',
       'S. E  2016-0076-39', 'S. E 2024-0089-14', 'S. E  2026-0083-93',
       'S.E.P 2026-0084-03', 'S. E   2014-0219-72', 'S.E P 2026-0084-14',
       'S.E 2018-0367-26', 'S.E 2026-0084-20', -2139,
       'SE-0254-2015-0133-92', 'S.E-2026-0048-79', 'S.E-2020-0191-76',
       'S.E-2025-0180-98', '2026-0084-50', 'S.  E   2026-0083-63',
       'S. E. P-2024-0106-97', 'S.E-2025-0317-44', 'S. E.-2026-0084-54',
       'S. E.-2026-0084-55', 'S. E.-2026-0084-61', 'S.E. 2022-0015-99',
       'S.E. 2026-0084-86', 'S.E. 2015-0231-62', 'S.E. 2021-0074-65',
       'S.E. 2023-0082-91', 'S. E.-2026-0085-02', 'S.E. 2025-0248-75',
       'S.E. 2022-0260-16', 'S.E. 2017-0134-91', 'S.E. 2025-0227-64',
       'S.E. 2019-0195-13', 'S.E. 2025-0252-00', 'S.E 2026-0085-75',
       'S.E-2019-0270-13', 'S.E-2014-0321-14', 'S. E  2023-0306-02',
       'S.E-2016-0179-63', 'S.E-2026-0073-64', 'S.E-2013-0151-59',
       'S. E 2013-0223-79', 'S.E. 2019-0194-94', 'S. E 2026-0086-07',
       'S. E  2013-0361-76', 'S.E 2026-0086-19', 'S. E. P 2023-0244-22',
       'S. E -2026-0086-21', 'S.E 2026-0086-26', 'S. E.-2026-0086-27',
       'S.E  2026-0086-39', 'S.E. 2025-0359-46', 'S.E 2016-0163-39',
       'S. E   -2026-0086-43', 'S. E2013-0333-79', 'S.E-2026-0047-13',
       'S.E-2015-0189-92', 'S.E-2026-0054-13', 'S.E-2026-0042-29',
       'S.E. 2023-0113-24', 'S. E.-2018-0013-27', 'S. E.-2016-0101-13',
       'S.E. 2016-0204-93', 'S.E. 2026-0087-18', 'S.E. 2024-0330-64',
       'S.E. 2025-0064-40', 'S.C. 2026-0087-57', 'S.E. 2026-0087-23',
       'S.E. 2026-0087-30', 'S.E 2023-0139-83', 'S.E. 2026-0087-44',
       'S.E. 2026-0087-45', 'S.E. 2025-0324-45', 'S.E.  2026-0087-46',
       'S.E. ', 'S.E. 2026-0087-69', 'S.E   2019-0308-67',
       'S.E 2017-0228-48', 'E.S 2026-0087-79', 'E. S  2019-0215-59',
       'S.E   2025-0185-11', 'S. E 2019-0186-17', 'S. E. P 2016-0247-51',
       'S.E -2026-0088-36', 'S. E  2016-0036-11', 'S.E 2018-0269-65',
       'S.E.P 2017-0347-88', 'S. E  2024-0130-57', 'S. E 2026-0088-91',
       'S. E P 2025-0243-77', 'S.E. 2022-182-14', 'S.E. 2023-0018-08',
       'S. E   2024-0136-72', 'S.E-2019-0273-69', 'S.E-2018-0006-08',
       'S.E. 2026-0090-38', 'S.E. 2023-0211-95', 'S.E-2026-0073-90',
       'S.E. 2023-0075-62', 'S.E. 2026-0090-62', 'S.E. 2026-0029-56',
       'S.E-2020-0061-76', 'S.E. 2022-0289-58', 'S.E. 2024-0192-76',
       'S.E. 2022-0099-08', 'S.E. 2026-0090-81', 'S.E. 2018-0166-83',
       'S.E. 2026-0059-28', 'S.E. 2024-0029-35', 'S.E. 2026-0091-20',
       'S.E. 2026-0091-24', 'S.E. 2026-0091-29', 'S.E.P-2025-0167-65',
       'S.E.P-2023-0021-80', 'S. E  2026-0091-56', 'S. E   2018-0129-84',
       'S.E 2016-0330-22', 'S.E 2026-0091-71', 'S.E 2026-0091-76',
       'S. E.-2026-0091-86', 'S.E.P 2026-0091-88', 'S. E  2026-0091-94',
       'S.  E   2026-0091-99', 'S. E   2025-0256-06', 'S.E 2026-0092-05',
       'S. E 2023-0125-50', 'S. E   2026-0092-19', 'S. E  2018-0028-60',
       'S.E 2022-0233-79', 'S. E  2026-0092-39', 'S. E  2018-0003-99',
       'S. E  2026-0092-44', 'S. E. P ', 'S. E 2025-0017-23',
       'S.E 2017-0295-57', 'S. E 2023-0015-99', 'S. E 2026-0092-53',
       'S. E 2019-0010-50', 'S. E   2026-0092-57', 'S.E 2018-0372-17',
       'S.E 2026-0092-73', 'S.E-', 'S.E. 2025-0166-79',
       'S.E. 2014-0282-63', 'S.E-2026-0093-18', 'S. E.-2025-0324-82',
       'S.E. 2026-0093-22', 'S.E. 2023-0016-20', 'S.E. 2026-0068-68',
       'S.E. 2026-0093-39', 'S.E. 2026-0093-38', 'S.E. 2023-0155-57',
       'S.E. 2025-0138-70', 'S.E-2026-0093-63', 'S.E-2026-0093-61',
       'S.E. 2026-0093-56', 'S.E. 2013-0324-18', 'S.E. 2026-0093-79',
       'S.E. 2024-0111-95', 'S.E. 2026-0093-85'], dtype=object)

In [ ]:
# Estadísticas descriptivas del DataFrame
df.describe()

,IdConsulta,IdCorrelativo,IdTenant,FechaHora,Turno,IdClinica,IdTipoClinica,IdServicio,IdDepartamentoHospitalario,HistoriaClinica,...,Papanicolaou,IVAA,TamizajeVIFVBG,CrecimientoYDesarrollo,FueReferido,VieneContraReferido,VieneReferido,FueContraReferido,SincronizarPaciente,SincronizarConsulta
count,190140.000000,190140.000000,190140.0,190140,190140.000000,190140.000000,190140.000000,190140.000000,190140.000000,1.901390e+05,...,190140.000000,190140.000000,190140.000000,190140.000000,190140.000000,190140.000000,190140.000000,190140.000000,190140.0,190140.0
mean,60976.949947,2024.851036,254.0,2025-05-11 20:34:35.309820,4106.482697,226.625439,1.795787,38.692584,3.591853,2.542820e+12,...,0.000536,0.000037,0.000011,0.041938,0.003282,0.000131,0.010713,0.000053,1.0,1.0
min,1.000000,2001.000000,254.0,2024-01-31 21:18:20.460000,1.000000,24.000000,1.000000,2.000000,1.000000,2.010334e+09,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,28102.750000,2024.000000,254.0,2024-12-23 12:03:28.617250,1894.000000,29.000000,2.000000,37.000000,1.000000,2.542019e+12,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
50%,56549.000000,2025.000000,254.0,2025-05-03 14:41:42.563000,4008.000000,66.000000,2.000000,37.000000,3.000000,2.542024e+12,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
75%,94896.250000,2025.000000,254.0,2025-09-19 09:37:37.372250,6162.250000,70.000000,2.000000,54.000000,4.000000,2.542025e+12,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
max,126025.000000,2026.000000,254.0,2026-03-25 23:48:42.060000,10349.000000,2109.000000,2.000000,68.000000,22.000000,2.054201e+13,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0
std,37267.048898,0.625924,0.0,NaN,2531.480283,404.004113,0.403126,19.162851,3.244942,1.240906e+11,...,0.023155,0.006067,0.003243,0.200447,0.057193,0.011466,0.102949,0.007252,0.0,0.0

In [5]:
df['TipoClinica'].unique()

<StringArray>
['CONSULTA EXTERNA', 'EMERGENCIA']
Length: 2, dtype: str

In [25]:
# df[df['EdadAnios'] > 60]
df[df["EdadAnios"] > 60][["EdadAnios", "Sexo", "Clinica", "Diagnostico"]]

,EdadAnios,Sexo,Clinica,Diagnostico
6,67,F,EMI-EMER Medicina Interna,EPOC
13,64,F,ET-EMER Traumatología,FRACTURA TIPO NEER 3 HOMBRO DERECHO
18,70,M,MH- Medicina Hombres,HTA NEUROPATIA
21,66,F,CM-CIRUGIA MUJERES,TUMOR RETROPERITONEAL
25,65,F,Gi-Ginecologia,PROLAPSO UTERINO GRADO IV
...,...,...,...,...
190074,70,F,EMI-Emergencia Medicina Interna,RESFRIADO COMUN
190076,67,F,EMI-Emergencia Medicina Interna,HTA
190105,70,M,EMI-Emergencia Medicina Interna,ITU
190110,64,F,EMI-Emergencia Medicina Interna,ENFERMEDAD RENAL CRONICA KDIGO V
190125,71,M,EMI-Emergencia Medicina Interna,ITU

In [ ]:
# cuantos menores de edad hay
df[df["EdadAnios"] < 18].shape[0]

66904

In [ ]:
# df["FechaNacimiento"].isna().sum()
df[(df["FechaNacimiento"].notna()) & (df["Sexo"] =="M")][["FechaNacimiento", "Sexo", "Clinica", "Diagnostico"]]
df[df["Sexo"] =="M"][["FechaNacimiento", "Sexo", "Clinica", "Diagnostico"]]

,FechaNacimiento,Sexo,Clinica,Diagnostico
9,NaT,M,PE-Pediatria,NEUMONIA
10,NaT,M,PE-Pediatria,NIÑO SANO
11,NaT,M,PE-Pediatria,TIÑA CAPITIS
16,NaT,M,PE-Pediatria,COLELITIASIS
17,NaT,M,PE-Pediatria,RESFRIADO COMUN
...,...,...,...,...
190135,1981-12-03,M,EMI-Emergencia Medicina Interna,HTA
190136,2007-10-31,M,EMI-Emergencia Medicina Interna,RESFRIADO COMUN
190137,2001-09-02,M,ET-Emergencia Traumatología,Contusión de hombro derecho.
190138,2011-06-18,M,EC-Emergencia Cirugía,herida cortoncontundente en pierna izquierda
190139,2016-08-27,M,EP-Emergencia Pediatrica,GASTROENTERITIS VIIRAL